import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import styles from '../styles/Home.module.css'

export default function Home() {
  const [items,setItems]=useState([
    { name:'ProductName', prize:'$50', image:'./sample.png', status:true,},
    { name:'ProductName', prize:'$50', image:'./sample.png', status:true,},
    { name:'ProductName', prize:'$50', image:'./sample.png', status:true,},
    { name:'ProductName', prize:'$50', image:'./sample.png', status:true,},
    { name:'ProductName', prize:'$50', image:'./sample.png', status:true,},
    { name:'ProductName', prize:'$50', image:'./sample.png', status:true,},
    { name:'ProductName', prize:'$50', image:'./sample.png', status:true,},
    { name:'ProductName', prize:'$50', image:'./sample.png', status:true,},
    { name:'ProductName', prize:'$50', image:'./sample.png', status:true,},
  ]);
  return (
    <div className='container'>
      <Head>
        <title>More To Buy</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className='header'></div>
      <div className='sidePanel'></div>
      <div className='productsContainer'>
      {items.map(I=>{
          return(<Item item={I}/>)
        })}
      </div>
    </div>
  );
}

const Item =({item})=>{
  return(
    <div className='item'>
      <img src={item.image}/>
      <h2>{item.name}</h2>
      <h3>{item.prize}</h3>
    </div>
  )
}
