import Head from 'next/head'
import { useEffect, useState } from 'react';
import wishlist from '../styles/Wishlist.module.css';
import Nav from '../Nav.js';
import LoginPopup from '../LoginPopup';
import {initFireBase} from '../firebase/client';
import {GoogleAuthProvider,signInWithPopup,getAuth} from 'firebase/auth'

export default function Home() {

  //states
  const [user,setUser]=useState(null);
  const [items,setItems]=useState([]);
  
  
  //firebase
  const app=initFireBase();
  const provider=new GoogleAuthProvider();
  const auth = getAuth(app);

  const signout=async ()=>{ 
    await auth.signOut();
  }


  //effects
  useEffect(()=>{
    //auto login
    auth.onAuthStateChanged(user=>{
      if(user){
        setUser({
          username:auth.currentUser.displayName,
          displayname:auth.currentUser.displayName,
          profilepic:auth.currentUser.photoURL,
          email:auth.currentUser.email,
          uid:auth.currentUser.uid,
        });
      }else{
        setUser(null);
      }
    });
  },[]);
  useEffect(()=>{
    if(user){loadData();}
  },[user]);

  const loadData=async ()=>{
    if(user){
        let token=await auth.currentUser.getIdToken();
        let xhr =new XMLHttpRequest();
        xhr.open('POST','/api/wishlist');
        xhr.setRequestHeader('Content-Type','application/json');
        xhr.send(JSON.stringify({
            uid:user.uid,
            token:token,
        }));
        xhr.onload=()=>{
            let d=JSON.parse(xhr.responseText);
            if(!d.error){
                setItems(d.data);
                
            }
        }
  }  
}
const dropFromWishlist=async (id)=>{
  if(user){
    let token=await auth.currentUser.getIdToken();
    let xhr = new XMLHttpRequest();
    xhr.open('POST','/api/dropfromwishlist');
    xhr.setRequestHeader('Content-Type','application/json');
    xhr.send(JSON.stringify({
      uid:user.uid,
      token:token,
      productID:id,
    }));
    xhr.onload=()=>{
      let d=JSON.parse(xhr.responseText);
      if(!d.error){
        loadData();
      }
    }
  }
}
  return (
    <>{user?
      <div className={wishlist.container}>
      <Head>
        <title>More To Buy</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Nav user={user} signout={signout}/>
      <div className={wishlist.header}>
        <input type="text" className={wishlist.input} placeholder='Search'/>
        <div className='button' onClick={()=>{}}>Search</div>
        <img className={wishlist.profilepic} src={user.profilepic}/>
      </div>
      <div className={wishlist.products}>
        {items.map(p=>{
          return(
            <Item item={p} dropFromWishlist={dropFromWishlist}/>
          )
        })}
      </div>
      </div>
      :
      <LoginPopup/>
  }</>
  );
}

const Item =({item,dropFromWishlist})=>{
  return(
    <div className='item'>
      <img src={item.image} onClick={()=>{window.location='/'+item.id}}/>
      <h2>{item.name}</h2>
      <h3>${item.prize}</h3>
      <div className='button' onClick={()=>{dropFromWishlist(item.id)}}>Remove</div>
    </div>
  )
}

